include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ONPrefs
ONPrefs_FILES = ONPrefsListController.m
ONPrefs_INSTALL_PATH = /Library/PreferenceBundles
ONPrefs_FRAMEWORKS = UIKit
ONPrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
